lane :update_dependencies_inside_example_projects do
  sh "bundle exec pod repo update"

  examples_dir = "../Examples"
  Dir.foreach(examples_dir) do |dir|
    if dir == ".."
      next
    end
    if dir == "."
      next
    end

    full_dir = examples_dir + "/" + dir
    is_dir = File.directory?(full_dir)

    if is_dir
      if not File.exists?(full_dir + "/" + "Podfile")
        next
      end

      sh "cd #{full_dir}; bundle exec pod update"
    end
  end
end
