platform :ios, '13.0'

target 'TableViewsSync' do
  use_frameworks!

  pod 'Highway', path: '../../', testspecs: ["HighwayTests"]
  pod 'Kingfisher', '~> 7.0'
  
  target 'TableViewsSyncTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
