platform :ios, '13.0'

target 'InfiniteScroll' do
  use_frameworks!

  pod 'Highway', path: '../../', testspecs: ["HighwayTests"]

  pod 'Swinject'
  pod 'SwiftMessages', :inhibit_warnings => true

  target 'InfiniteScrollTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Sourcery', :subspecs => ['CLI-Only']
    pod 'SnapshotTesting'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
